services:
  - type: web
    name: rafeeq
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_PASSWORD
        sync: false